apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-website-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-website
  template:
    metadata:
      labels:
        app: simple-website
    spec:
      containers:
      - name: simple-website
        image: shubhamsaraf26/simple-website:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: simple-website-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: simple-website
